kids_interactive_learning/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_user, name='logout'),
    path('home/', views.home, name='home'),
    path('add_course/', views.add_course, name='add_course'),
    path('course_details/<int:cid>', views.view_course, name='view_course'),
    path('dashboard/<int:cid>', views.marks, name='marks'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('1/', views.testgame, name='testgame'),
    path('2/', views.mathgame, name='mathgame'),
    path('3/', views.shapegame, name='shapegame'),
    path('happy/<slug:user>/<int:happy>', views.happy, name='happy'),
    path('', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/templates/web/add_course.html
{% extends 'web/base_guide.html' %}
{% load bootstrap4 %}
{% block title %}Create a course{% endblock %}
{% block addcourseactive %}active{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card" style="margin-top: 1em">
                <div class="card-body">
                    <h3>Create a course</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form role="form" action="{% url 'web:add_course'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Create</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

web/templates/web/approval.html
{% extends 'web/base_visitor.html' %}
{% load bootstrap4 %}
{% block title %}Register{% endblock %}
{% block registeractive %}active{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card" style="margin-top: 1em">
                <div class="card-body">
                    <h3>Register</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                </div>
                <div class="card-footer">
                    Already have an account? <a href="{% url 'web:login' %}">Click here</a> to login!
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

web/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap-4.0.0-dist/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-4.0.0-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'web:index' %}">NITKLearn</a>
      <div class="collapse navbar-collapse" id="navbarNav">
          {% block menu %}
          {% endblock %}
      </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

web/templates/web/base_guide.html
{% extends 'web/base.html' %}
{% block menu %}
    <ul class="navbar-nav">
        <li class="nav-item {% block homeactive %}{% endblock %}">
            <a class="nav-link" href="{% url 'web:home' %}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% block dashboardactive %}{% endblock %}" href="{% url 'web:dashboard' %}">Dashboard</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% block addcourseactive %}{% endblock %}" href="{% url 'web:add_course' %}"><i class="fa fa-plus"></i>&nbsp; Add course</a>
        </li>
    </ul>
    <ul class="nav-pills navbar-nav mr-auto"></ul>
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'web:logout' %}"><i class="fa fa-power-off"></i>&nbsp; Log Out</a>
        </li>
    </ul>
{% endblock %}

web/templates/web/base_student.html
{% extends 'web/base.html' %}
{% block menu %}
<ul class="navbar-nav">
  <li class="nav-item {% block homeactive %}{% endblock %}">
    <a class="nav-link" href="{% url 'web:home' %}">Home</a>
  </li>
</ul>
<ul class="nav-pills navbar-nav mr-auto"></ul>
<ul class="navbar-nav">
  <li class="nav-item">
      <a class="nav-link" href="{% url 'web:logout' %}"><i class="fa fa-power-off"></i>&nbsp; Log Out</a>
</ul>
{% endblock %}

web/templates/web/dashboard.html
{% extends 'web/base_guide.html' %}
{% block title %}Dashboard{% endblock %}
{% block dashboardactive %}active{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-6" style="margin-top: 1.0em">
                <h3 style="color: #007bff;">Dashboard</h3>
                <div class="container-fluid" style="margin-top: 0.5em">
                    <div class="row">
                        {% if courses %}
                            {% for course in courses %}
                                <div class="card col-3" style="width:30%; padding: 0.5em; margin: 0.5em">
                                    <a href="#">
                                        <img src="{{ course.thumbnail.url }}" class="card-img-top img-fluid" style="padding: 0.5em">
                                    </a>
                                    <div class="card-body">
                                        <h5 class="card-title">
                                            {{ course.name }}
                                        </h5>
                                        <p class="card-text">
                                            {{ course.description }}
                                        </p>
                                        <a class="btn btn-primary" href="{% url 'web:view_course' course.id %}">Details</a>
                                        <a class="btn btn-primary marks" id="{{ course.id }}" href="#">Marks</a>
                                    </div>
                                </div>
                                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-6" style="margin-top: 1.5em">
                <iframe id="frame" width="100%" src="#" style="border: ActiveBorder" height="100%"></iframe>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function() {
           $('body').on('click', '.marks', function () {
               var course_id = $(this).attr('id');
               var iframe = document.getElementById('frame');
               iframe.src = location.protocol + '//' + location.host + location.pathname + course_id;
           })
        });
    </script>
{% endblock %}

web/templates/web/login.html
{% extends 'web/base_visitor.html' %}
{% block title %}Login{% endblock %}
{% block loginactive %}active{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card" style="margin-top: 1em">
                <div class="card-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'web:login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Login</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    Don't have an account? <a href="{% url 'web:register' %}">Click here</a> to register!
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

web/templates/web/mathgame.html
{% extends 'web/base_student.html' %}
{% block title %}Math game{% endblock %}
{% load staticfiles %}
{% block head %}
    <meta http-equiv="content-type" content="text/html; charset=windows-1252">
    <style type="text/css">
        img {
            border: none;
        }

        .mathe_game_bg {
            margin: 0 auto;
            background: url({% static 'images/math_game_bg.png' %}) no-repeat;
            width: 700px;
            height: 400px;
        }

        .mathe_game_head {
            margin: 105px auto 0;
        }

        .display {
            background: none;
            border: none;
            font: bold 45px Arial, Helvetica, sans-serif;
            text-align: center;
        }

        .mathe_game_foot {
            margin: 73px auto 0;
        }

        .plus_button {
            background: url({% static 'images/plus.png' %}) no-repeat;
            width: 74px;
            height: 35px;
            border: none;
        }

        .minus_button {
            background: url({% static 'images/minus.png' %}) no-repeat;
            width: 74px;
            height: 35px;
            border: none;
        }

        .multiply_button {
            background: url({% static 'images/multiply.png' %}) no-repeat;
            width: 74px;
            height: 35px;
            border: none;
        }

        .divide_button {
            background: url({% static 'images/divide.png' %}) no-repeat;
            width: 74px;
            height: 35px;
            border: none;
        }

        .math_txt {
            width: 80px;
            height: 30px;
            background: none;
            border: none;
            text-align: center;
            font: bold 14px Arial, Helvetica, sans-serif;
        }
    </style>

    <script type="text/javascript">
        shuffle = function (o) {
            for (var j, x, i = o.length; i; j = parseInt(Math.random() * i), x = o[--i], o[i] = o[j], o[j] = x) ;
            return o;
        };

        var arr = new Array();
        var arr1 = new Array("5 ? 2 = 10#779", "56 ? 34 = 22#275", "9 ? 1 = 10#133", "92 ? 2 = 46#384", "5 ? 2 = 3#275", "4 ? 6 = 10#133",
            "10 ? 2 = 5#384", "7 ? 5 = 12#133", "45 ? 2 = 90#779", "6 ? 3 = 2#384", "6 ? 6 = 36#779", "54 ? 12 = 42#275",
            "63 ? 9 = 7#384", "24 ? 6 = 144#779", "34 ? 11 = 23#275", "121 ? 11 = 11#384", "67 ? 21 = 46#275", "13 ? 47 = 60#133",
            "56 ? 7 = 8#384", "97 ? 42 = 55#275", "77 ? 1 = 77#779", "27 ? 3 = 9#384", "63 ? 2 = 126#779", "78 ? 45 = 33#275", "45 ? 9 = 5#384");

        var arr2 = new Array("41 ? 12 = 29#275", "91 ? 57 = 148#133", "6 ? 4 = 2#275", "7 ? 3 = 21#779", "4 ? 13 = 52#779", "15 ? 3 = 5#384",
            "3 ? 12 =36#779", "65 ? 5 = 13#384", "51 ? 27 =78#133", "62 ? 18 =80#133", "7 ? 5 = 35#779", "21 ? 17 = 4#275",
            "37 ? 15 = 52#133", "16 ? 3 = 48#779", "1 ? 2 = 2#779", "3 ? 1 =2#275", "81 ? 6 = 75#275", "7 ? 28 = 35#133",
            "23 ? 19 = 42#133", "51 ? 20 =31#275", "63 ? 27 = 90#133", "62 ? 2 =31#384", "66 ? 3 = 22#384", "37 ? 51 =88#133", "77 ? 11 = 7#384");

        var arr3 = new Array("16 ? 4 = 4#384", "47 ? 32 = 15#275", "23 ? 3 = 69#779", "71 ? 23 = 94#133", "67 ? 29 = 96#133", "51 ? 3 = 153#779", "7 ? 14 = 98#779",
            "57 ? 13 = 44#275", "85 ? 13 = 72#275", "51 ? 3 =17#384", "53 ? 25 =78#133", "17 ? 2 = 34#779", "29 ? 7 = 22#275", "22 ? 15 = 37#133",
            "13 ? 6 = 78#779", "1 ? 2 = 3#133", "13 ? 7 =6#275", "81 ? 6 = 75#275", "32 ? 2 = 16#384", "26 ? 43 = 67#133", "87 ? 21 = 108#133",
            "49 ? 7 = 7#384", "69 ? 12 = 81#133", "3 ? 43 = 129#779", "66 ? 6 = 11#384");

        var arr4 = new Array("42 ? 2 =21#384", "17 ? 7 = 24#275", "19 ? 3 = 57#779", "27 ? 4 = 31#133", "5 ? 5 = 25#779", "41 ? 15 =26#275", "29 ? 6 = 35#133",
            "43 ? 17 = 26#275", "7 ? 6 = 42#779", "86 ? 2 = 43#384", "35 ? 14 = 49#133", "71 ? 14 = 57#275", "64 ? 4 = 16#384", "15 ? 5 = 75#779",
            "90 ? 10 = 9#384", "48 ? 6 = 8#384", "31 ? 27 = 58#133", "28 ? 4 = 7#384", "6 ? 7 = 42#779", "54 ? 9 = 6#384", "67 ? 23 = 44#275",
            "77 ? 12 = 65#275", "9 ? 3 = 27#779", "36 ? 4 = 9#384", "8 ? 8 = 64#779");

        var arr5 = new Array("32 ? 1 = 33#133", "7 ? 5 = 35#779", "11 ? 2 = 9#275", "6 ? 17 = 23#133", "9 ? 3 = 3#384", "83 ? 17 = 66#275", "53 ? 12 = 65#133",
            "37 ? 2 =74#779", "3 ? 4 = 12#779", "63 ? 3 = 21#384", "108 ? 3 = 36#384", "39 ? 23 = 16#275", "19 ? 7 = 26#133", "74 ? 2 = 148#779",
            "53 ? 79 = 132#133", "6 ? 9 = 54#779", "97 ? 16 = 81#275", "87 ? 43 = 130#133", "31 ? 69 = 100#133", "52 ? 19 = 33#275", "68 ? 4 = 17#384",
            "39 ? 7 = 46#133", "4 ? 4 = 16#779", "42 ? 7 = 6#384", "44 ? 15 = 59#133");
        var anscorrect = 0;
        var answrong = 0;
        var noq = 25;
        var pos = 0;
        var ques, ans, moves;
        var count = 0;
        var timee = 100;
        //var ref=Math.floor(Math.random()*5);
        var ref = 0;
        var suff = shuffle(arr);
        var finished = 0;
        var firstmove = 0;
        var level = 1;
        Array.prototype.inArray = function (value) {
            var i;
            for (i = 0; i < this.length; i++) {
                if (this[i] === value) {
                    return true;
                }
            }
            return false;
        };

        function next() {
            count = anscorrect + answrong;
            if (eval(document.getElementById('tim').value) !== 0) {
                start();
            }
        }

        function click_op(sss) {
            if (firstmove > 0 && finished == 0) {
                var chk = parseInt(sss);
                var calc = ques.split('');
                var ope1 = calc[0];
                var ope2 = calc[2];
                if (ans == chk) {
                    anscorrect = anscorrect + 1;
                    document.getElementById('right').value = anscorrect;
                    next();
                }
                else {
                    answrong = answrong + 1;
                    document.getElementById('wrong').value = answrong;
                    next();
                }
            }
        }

        function refresh() {
            document.location.reload();
            document.getElementById('tim').value = '';
            document.getElementById('right').value = 0;
            document.getElementById('wrong').value = 0;
        }

        function start_play() {
            if (firstmove === 0) {
                timedCount();
                firstmove++;
            }
        }

        var t;

        function timedCount() {
            if (t) clearTimeout(t);
            if (eval(document.getElementById('tim').value) !== 0) {
                document.getElementById('tim').value = timee;
                timee = timee - 1;
                t = setTimeout("timedCount()", 1000);
            }
            else if (eval(document.getElementById('tim').value) === 0) {
                //alert("df")
                finished = 1;
                document.getElementById('tim').value = '';
                moves = document.getElementById('right').value;
                negative = document.getElementById('wrong').value;
                //alert(moves+"=="+negative)
                var marks = moves * 2 - negative;
                if ((moves > negative && moves !== 0)) {
                    //Make the AJAX call here!
                    document.getElementById("msg").innerHTML = "You have won it....!";
                    timee = 120;
                    //sAjaxa(moves,timee,'reverse','');
                }
                else {
                    document.getElementById("msg").innerHTML = "You have lost it....!";
                }
                $.post({% url 'web:mathgame' %},{
                        marks: marks
                    },function (data, status) {
                        alert(data);
                        window.location = {% url 'web:home' %};
                });
            }
        }


    </script>
    <link href="{% static 'css/getgamecode.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block body %}
<div class="mathe_game_bg">
    <table cellspacing="0" cellpadding="0" border="0" style="margin-top: 2em">
        <tbody>
        <tr>
            <td width="195" align="right"><img src="{% static 'images/refresh.png' %}"
                                               style="margin-top:160px;cursor:pointer;" onclick="refresh()"></td>
            <td>
                <table class="mathe_game_head" width="310" cellspacing="0" cellpadding="0" border="0">
                    <tbody>
                    <tr>
                        <td colspan="4" id="show" class="display" height="55">121 ? 11 = 11</td>
                    </tr>
                    <tr>
                        <td colspan="4">&nbsp;</td>
                    </tr>
                    <tr>
                        <td><input id="plus" onclick="click_op(133)" value="" class="plus_button"
                                   data-_extension-text-contrast="fg" type="submit"></td>
                        <td><input id="minus" onclick="click_op(275)" value="" class="minus_button"
                                   data-_extension-text-contrast="fg" type="submit"></td>
                        <td><input id="mul" onclick="click_op(779)" value="" class="multiply_button"
                                   data-_extension-text-contrast="fg" type="submit"></td>
                        <td><input id="div" onclick="click_op(384)" value="" class="divide_button"
                                   data-_extension-text-contrast="fg" type="submit"></td>
                    </tr>
                    </tbody>
                </table>
                <br>
                <table class="mathe_game_foot" width="310" cellspacing="0" cellpadding="0" border="0">
                    <tbody>
                    <tr>
                        <td width="87"><input id="right" readonly="readonly" class="math_txt"
                                              data-_extension-text-contrast="fg" type="text"></td>
                        <td width="25">&nbsp;</td>
                        <td width="90"><input id="wrong" readonly="readonly" class="math_txt"
                                              data-_extension-text-contrast="fg" type="text"></td>
                        <td width="15">&nbsp;</td>
                        <td><input class="math_txt" id="tim" readonly="readonly" data-_extension-text-contrast="fg"
                                   type="text"></td>
                    </tr>
                    </tbody>
                </table>
            </td>
            <td><img src="{% static 'images/play.png' %}" style="margin-top:160px;cursor:pointer;" onclick="start_play()"></td>
        </tr>
        <tr>
            <td id="msg" align="center"></td>
        </tr>
        </tbody>
    </table>

</div>
<script>

    function start() {
        if (ref === 0) {
            arr = shuffle(arr1);
            pos = Math.floor(Math.random() * arr1.length);
        }
        if (ref === 1) {
            arr = shuffle(arr2);
            pos = Math.floor(Math.random() * arr2.length);
        }
        if (ref === 2) {
            arr = shuffle(arr3);
            pos = Math.floor(Math.random() * arr3.length);
        }
        if (ref === 3) {
            arr = shuffle(arr4);
            pos = Math.floor(Math.random() * arr4.length);
        }
        if (ref === 4) {
            arr = shuffle(arr5);
            pos = Math.floor(Math.random() * arr5.length);
        }
        var fg = arr[pos];

        var gg = fg.split("#");
        ques = gg[0];
        ans = gg[1];
        var disp = document.getElementById('show');
        disp.innerHTML = gg[0];
    }
    start();
</script>
{% endblock %}

web/templates/web/register.html
{% extends 'web/base_visitor.html' %}
{% load bootstrap4 %}
{% block title %}Register{% endblock %}
{% block registeractive %}active{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card" style="margin-top: 1em">
                <div class="card-body">
                    <h3>Register</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form role="form" action="{% url 'web:register'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form uform %}
                        {% bootstrap_form pform %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Register</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    Already have an account? <a href="{% url 'web:login' %}">Click here</a> to login!
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

web/templates/web/shapegame.html
{% extends 'web/base_student.html' %}
{% load staticfiles %}
    {% load bootstrap4 %}
		{% block title %}Shapes Game{% endblock %}
        {% block head %}
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <style>
              * {
                  box-sizing: border-box;
              }

              /* Create two equal columns that floats next to each other */
              .row {
                  {#float: left;#}
                  .center-block
                  width: 20%;
                  padding-left: 100px;
              }

              /* Clear floats after the columns */
              .row:after {
                  content: "";
                  display: table;
                  clear: both;
              }
              #div_squ, #div_tri, #div_circ, #drop_tri, #div_dia, #drop_squ, #drop_cir, #drop_dia {
                  float: left;
                  width: 102px;
                  height: 102px;
                  clear:both;
                  border: 0px ;
              }
              #drop_tri, #drop_cir, #drop_dia, #drop_squ{
                border: 1px solid black;

              }
              p{
                clear: both;
              }
            </style>
            <script>
              var allow_drag = true;
              function allowDrop(ev) {
                  ev.preventDefault();
              }

              function drag(ev) {
                  ev.dataTransfer.setData("text", ev.target.id);
              }

              function drop(ev) {
                  ev.preventDefault();
                  var data = ev.dataTransfer.getData("text");
                  // if (ev.target.childNodes.length == 1 ) { // Or just `if (element.childNodes.length)`
                // It has at least one
                    var children = ev.target.childNodes.length;
                    var target_id = ev.target.id;
                    var drop_start = target_id.startsWith("drop");
                    var div_start = target_id.startsWith("div");
                    if (drop_start === true && children == 1)
                      ev.target.appendChild(document.getElementById(data));
                    if(div_start==true && children == 2 )
                      ev.target.appendChild(document.getElementById(data));
                  // }
                  //Put an if condition over here
                  if ($allow_drag)
                    document.getElementById(ev.target.id).setAttribute("ondrop", "return false;")
                  else {
                    $allow_drag = true;
                    document.getElementById(ev.target.id).setAttribute("ondrop", "return true;")
                  }
                function total_score() {

                }
              }
            </script>
        {% endblock %}

        {% block body %}

            <div class="row container-fluid">
                <div class="col-sm-5 col-md-5 col-lg-5" style=".block-center; height: 100vh">
                    <h2>Shapes</h2>
                    <div id="div_tri" ondrop="drop(event)" ondragover="allowDrop(event)" style=" margin-top: 5vh">
                        <img src="{% static 'images/triangle.png' %}" draggable="true" ondragstart="drag(event)" id="tri_drag" width="100" height="100">
                    </div>
                    <div id="div_squ" ondrop="drop(event)" ondragover="allowDrop(event)" style=" margin-top: 5vh">
                        <img src="{% static 'images/square.png' %}" draggable="true" ondragstart="drag(event)" id="squ_drag" width="100" height="100">
                    </div>
                    <div id="div_circ" ondrop="drop(event)" ondragover="allowDrop(event)" style=" margin-top: 5vh">
                        <img src="{% static 'images/circle.png' %}" draggable="true" ondragstart="drag(event)" id="cir_drag" width="100" height="100">
                    </div>
                    <div id="div_dia" ondrop="drop(event)" ondragover="allowDrop(event)" style=" margin-top: 5vh">
                        <img src="{% static 'images/diamond.png' %}" draggable="true" ondragstart="drag(event)" id="dia_drag" width="100" height="100">
                    </div>
                </div>

                <div class="col-sm-5 col-md-5 col-lg-5">
                    <h2>Names</h2>
                    <div id="drop_tri" ondrop="drop(event)" ondragover="allowDrop(event)">
                    </div>
                    <p>Triangle</p>
                    <div id="drop_dia" ondrop="drop(event)" ondragover="allowDrop(event)">
                    </div>
                    <p>Diamond</p>
                    <div id="drop_squ" ondrop="drop(event)" ondragover="allowDrop(event)">
                    </div>
                    <p>Square</p>
                    <div id="drop_cir" ondrop="drop(event)" ondragover="allowDrop(event)">
                    </div>
                <p>Circle</p>
                </div>

                <form class="form-group" action="#" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
{#                    This is making the website really hackable? I mean, scores, hackable. #}
                    <input type="hidden" text="" name="resultstatus" value="" id="resultstatus">
                    <div class="col-sm-1 col-md-1 col-lg-1" style=".block-center; height: 100vh">
                        <input type="submit" value="Submit" onclick="submit_shapegame_answer();" style=" margin-top: 50vh">
                    </div>
                </form>

            </div>

            <script>
                function submit_shapegame_answer(event){
                    try{
                        var ans1 = document.getElementById('drop_tri').children[0].id === 'tri_drag';
                        var ans2 = document.getElementById('drop_dia').children[0].id === 'dia_drag';
                        var ans3 = document.getElementById('drop_squ').children[0].id === 'squ_drag';
                        var ans4 = document.getElementById('drop_cir').children[0].id === 'cir_drag';

                        var x = Array(ans1, ans2, ans3, ans4);
                        var maxscore = x.length;
                        var score = 0;
                        x.forEach(
                            function(entry) {
                                if (entry == 1){
                                    score += 1;
                                }
                            }
                        );
                        var msg = score.toString() + "/" + maxscore.toString();
                        document.getElementById('resultstatus').value = msg;
                        $.post("{% url 'web:shapegame' %}",{
                            marks: msg
                        },function (data, status) {
                            alert(data);
                            window.location = {% url 'web:home' %};
                        });

                    } catch (err) {
                        if (err.message === "Cannot read property 'id' of undefined"){
                            window.alert("Answer all questions");
                        }else {
                            window.alert("Some error has occurred.");
                            window.location = "{% url 'web:shapegame' %}";
                        }
                    }
                }
            </script>
        {% endblock %}